### PR TITLE
added cross-env

### PR DESCRIPTION
**Pull request by NileshPatel17**

### CODE REVIEW

**Comment by deeppatel234** [comment]
Hello, thank you for your contribution.
Can you please remove packages.lock.json file

**Comment by NileshPatel17** [comment]
As a new package is being added, hence kept package.lock.json. It should be keep in sync whenever a new package is added. let me your view. Still if you want to remove, i will remove it.

**Comment by deeppatel234** [comment]
yes, I understand this but this is an example to test the library. so please remove it

**Comment by NileshPatel17** [comment]
Done. I thought i updated the lock file but in fact it was added by me.  Removed it.

**Pull request merged**
